// ─────────────────────────────────────────────────────────────────────────────
// Medicine-name detection for the output guard.
//
// The guard's rule is: a medicine the reply names must be one the patient's
// record, the question, or the kept conversation already names. To apply it,
// the guard first has to recognise a medicine name — without a full drug
// database, and without mistaking "cholesterol", "alcohol" or "control" for
// one (v1 did: its bare "-ol" suffix flagged ordinary words and blocked
// correct answers about lipids).
//
// Two layers, both case-insensitive:
//   1. a lexicon of generics common in Indian stroke, cardiac, diabetes and
//      general practice, including the ones whose names fit no suffix;
//   2. drug-family suffixes that essentially never end an English word.
// A short stoplist catches the English words that do end in a family suffix.
// ─────────────────────────────────────────────────────────────────────────────

const LEXICON = [
  // Antiplatelets, anticoagulants, thrombolytics
  'aspirin',
  'clopidogrel',
  'prasugrel',
  'ticagrelor',
  'cilostazol',
  'dipyridamole',
  'warfarin',
  'acenocoumarol',
  'heparin',
  'enoxaparin',
  'dalteparin',
  'fondaparinux',
  'dabigatran',
  'apixaban',
  'rivaroxaban',
  'edoxaban',
  'alteplase',
  'tenecteplase',
  // Lipids
  'atorvastatin',
  'rosuvastatin',
  'simvastatin',
  'pravastatin',
  'pitavastatin',
  'ezetimibe',
  'fenofibrate',
  'bempedoic',
  'evolocumab',
  'inclisiran',
  // Blood pressure, heart
  'amlodipine',
  'cilnidipine',
  'nifedipine',
  'felodipine',
  'telmisartan',
  'losartan',
  'olmesartan',
  'valsartan',
  'irbesartan',
  'candesartan',
  'ramipril',
  'enalapril',
  'lisinopril',
  'perindopril',
  'metoprolol',
  'bisoprolol',
  'carvedilol',
  'atenolol',
  'nebivolol',
  'propranolol',
  'labetalol',
  'hydrochlorothiazide',
  'chlorthalidone',
  'indapamide',
  'furosemide',
  'torsemide',
  'spironolactone',
  'eplerenone',
  'prazosin',
  'clonidine',
  'methyldopa',
  'hydralazine',
  'isosorbide',
  'nitroglycerin',
  'ranolazine',
  'ivabradine',
  'digoxin',
  'amiodarone',
  'sacubitril',
  // Diabetes, thyroid
  'metformin',
  'glimepiride',
  'gliclazide',
  'glipizide',
  'sitagliptin',
  'vildagliptin',
  'linagliptin',
  'teneligliptin',
  'dapagliflozin',
  'empagliflozin',
  'canagliflozin',
  'pioglitazone',
  'acarbose',
  'voglibose',
  'insulin',
  'semaglutide',
  'liraglutide',
  'dulaglutide',
  'levothyroxine',
  'thyroxine',
  'carbimazole',
  'methimazole',
  // Neuro, mood, spasticity
  'levetiracetam',
  'phenytoin',
  'valproate',
  'carbamazepine',
  'lacosamide',
  'clobazam',
  'gabapentin',
  'pregabalin',
  'amitriptyline',
  'nortriptyline',
  'duloxetine',
  'escitalopram',
  'citalopram',
  'sertraline',
  'fluoxetine',
  'mirtazapine',
  'donepezil',
  'memantine',
  'baclofen',
  'tizanidine',
  'citicoline',
  'piracetam',
  'nimodipine',
  'alprazolam',
  'lorazepam',
  'clonazepam',
  'diazepam',
  'zolpidem',
  'melatonin',
  // Pain, stomach, allergy, chest
  'paracetamol',
  'acetaminophen',
  'ibuprofen',
  'diclofenac',
  'naproxen',
  'aceclofenac',
  'etoricoxib',
  'tramadol',
  'pantoprazole',
  'omeprazole',
  'rabeprazole',
  'esomeprazole',
  'famotidine',
  'ranitidine',
  'ondansetron',
  'domperidone',
  'lactulose',
  'cetirizine',
  'levocetirizine',
  'fexofenadine',
  'montelukast',
  'salbutamol',
  'budesonide',
  'prednisolone',
  'dexamethasone',
  'methylprednisolone',
  'hydrocortisone',
  // Antibiotics
  'amoxicillin',
  'azithromycin',
  'doxycycline',
  'ciprofloxacin',
  'levofloxacin',
  'ceftriaxone',
  'cefixime',
  'nitrofurantoin',
  'metronidazole',
  // Supplements prescribed as medicines
  'cholecalciferol',
  'methylcobalamin',
  'cyanocobalamin',
  'folic acid',
] as const;

/** Drug-family endings that essentially never end an English word. */
const SUFFIXES = [
  'statin',
  'sartan',
  'pril',
  'dipine',
  'olol',
  'prazole',
  'gliptin',
  'gliflozin',
  'floxacin',
  'cillin',
  'mycin',
  'cycline',
  'parin',
  'xaban',
  'gatran',
  'grel',
  'glutide',
  'tidine',
  'setron',
  'triptan',
  'zepam',
  'zolam',
  'oxetine',
  'profen',
  'coxib',
  'teplase',
  'semide',
  'thiazide',
  'formin',
  'glinide',
  'mab',
];

/** English words that happen to end in a family suffix. */
const STOPLIST = new Set([
  'cholesterol',
  'alcohol',
  'control',
  'protocol',
  'school',
  'patrol',
  'petrol',
  'lab',
  'tab',
  'grab',
  'crab',
  'slab',
  'stab',
  'jab',
  'cab',
  'drab',
  'kebab',
  'prehab',
  'rehab',
  'swab',
  'mongrel',
]);

const LEXICON_RE = new RegExp(
  `\\b(${LEXICON.map((w) => w.replace(/ /g, '\\s+')).join('|')})\\b`,
  'gi',
);
const SUFFIX_RE = new RegExp(`\\b[a-z]{3,}(?:${SUFFIXES.join('|')})\\b`, 'gi');

/** Every medicine-like name in `text`, lowercase and de-duplicated. */
export function medicineNamesIn(text: string): string[] {
  const found = new Set<string>();
  for (const m of text.matchAll(LEXICON_RE)) found.add(m[0].toLowerCase().replace(/\s+/g, ' '));
  for (const m of text.matchAll(SUFFIX_RE)) {
    const w = m[0].toLowerCase();
    if (!STOPLIST.has(w)) found.add(w);
  }
  return [...found];
}
